// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zughojwkppzecdejdwuk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1Z2hvandrcHB6ZWNkZWpkd3VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDkxNzYsImV4cCI6MjA2NTQ4NTE3Nn0.Jt-GOaNDij9k7vlALfvRrVO6p5C92AF5MuQabt593R0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});